;;;; package.lisp

(defpackage #:jj
  (:use #:cl)
  (:import-from #:cl-containers
                #:simple-associative-container
                #:set-container
                #:array-container
                #:item-at
                #:find-item
                #:insert-item
                #:insert-new-item
                #:insert-item-at
                #:collect-items
                #:search-for-item
                #:search-for-match
                #:delete-item
                #:make-container
                #:list-container
                #:dlist-container
                #:vector-container
                #:delete-item
                #:delete-item-if
                #:delete-index
                #:some-element-p
                #:empty!
                #:empty-p
                #:append-item
                #:every-item-p
                #:iterate-container
                #:iterate-elements)
  (:import-from #:split-sequence
                #:split-sequence)
  (:export #:setting
           #:*settings*
           #:define-setting
           #:settings-layer
           #:make-settings-layer
           #:*global-settings*
           #:no-such-setting-error
           #:signal-no-such-setting-error
           #:calculate-tab-width
           #:leading-string-width
           #:find-setting
           #:set-setting
           #:get-setting
           #:tab-width
           #:string-has-prefix-p
           #:string-has-prefix-insensitive-p
           #:match-input-character
           #:match-regex
           #:combine-matches
           #:chord
           #:chord=
           #:chord-character-code
           #:chord-modifiers
           #:make-chord
           #:key-sequence
           #:key-sequence-keys
           #:key-sequence=
           #:parse-key-sequence
           #:make-key-sequence
           #:do-container
           #:container-append
           #:process-input
           #:clear-key-stroke-buffer
           #:clear-stroke-buffer-empty-p
           #:key-stroke-buffer-size
           #:*key-stroke-buffer*
           #:key-binding
           #:key-binding-activation-sequence
           #:key-binding-follow-sequences
           #:key-binding-action
           #:make-key-binding
           #:mode
           #:mode-key-bindings
           #:add-mode-binding
           #:create-mode-binding
           #:*current-mode*
           #:process-input
           #:buffer
           #:buffer-lines
           #:make-buffer
           #:buffer-lines-count
           #:buffer-line
           #:buffer-append
           #:read-file-into-buffer
           #:invalid-text-position-error
           #:signal-invalid-text-position-error
           #:text-position
           #:text-position-absolute-position
           #:text-position-line-number
           #:text-position-line-position
           #:make-text-position
           #:text-position=
           #:jj-error
           #:main))
